export const cards = [
    {
      id: 1,
      title: "Движун",
      imageSrc: "/images/cat.svg",
      background: "#ffe1e1",
    },
    {
      id: 2,
      title: "Полнолун",
      imageSrc: "/images/polnolun.svg",
      background: "#e7ecf3",
    },
    {
      id: 3,
      title: "Ааагонь",
      imageSrc: "/images/fire.svg",
      background: "#f2d7ff",
    },
    {
      id: 4,
      title: "Ееедаа",
      imageSrc: "/images/meal.svg",
      background: "#c3ffc9",
    },
    {
      id: 5,
      title: "На чиле",
      imageSrc: "/images/chill.svg",
      background: "#ffedcc",
    },
    {
      id: 6,
      title: "Поп Дог",
      imageSrc: "/images/dog.svg",
      background: "#ffe1e1",
    },
    {
      id: 7,
      title: "Кить-коть",
      imageSrc: "/images/cats.svg",
      background: "#d9e8fb",
    },
    {
      id: 8,
      title: "Пинк Пу",
      imageSrc: "/images/pink.svg",
      background: "#ffe1f0",
    },
    {
      id: 9,
      title: "Пельмешка",
      imageSrc: "/images/dumpling.svg",
      background: "#ffe1e1",
    },
    {
      id: 10,
      title: "Маска",
      imageSrc: "/images/mask.svg",
      background: "#c3fff4",
    },
    {
      id: 11,
      title: "Движун",
      imageSrc: "/images/cat.svg",
      background: "#ffe1e1",
    },
    {
      id: 12,
      title: "Полнолун",
      imageSrc: "/images/polnolun.svg",
      background: "#e7ecf3",
    },
    {
      id: 13,
      title: "Ааагонь",
      imageSrc: "/images/fire.svg",
      background: "#f2d7ff",
    },
    {
      id: 14,
      title: "Ееедаа",
      imageSrc: "/images/meal.svg",
      background: "#c3ffc9",
    },
    {
      id: 15,
      title: "На чиле",
      imageSrc: "/images/chill.svg",
      background: "#ffedcc",
    },
    {
      id: 16,
      title: "Поп Дог",
      imageSrc: "/images/dog.svg",
      background: "#ffe1e1",
    },
    {
      id: 17,
      title: "Кить-коть",
      imageSrc: "/images/cats.svg",
      background: "#d9e8fb",
    },
    {
      id: 18,
      title: "Пинк Пу",
      imageSrc: "/images/pink.svg",
      background: "#ffe1f0",
    },
    {
      id: 19,
      title: "Пельмешка",
      imageSrc: "/images/dumpling.svg",
      background: "#ffe1e1",
    },
    {
      id: 20,
      title: "Маска",
      imageSrc: "/images/mask.svg",
      background: "#c3fff4",
    },
    {
      id: 21,
      title: "Движун",
      imageSrc: "/images/cat.svg",
      background: "#ffe1e1",
    },
    {
      id: 22,
      title: "Полнолун",
      imageSrc: "/images/polnolun.svg",
      background: "#e7ecf3",
    },
    {
      id: 23,
      title: "Ааагонь",
      imageSrc: "/images/fire.svg",
      background: "#f2d7ff",
    },
    {
      id: 24,
      title: "Ееедаа",
      imageSrc: "/images/meal.svg",
      background: "#c3ffc9",
    },
  ];